### ISSUE TITLE
请问对软件的原始安装方式有要求吗？

### ISSUE THREAD

**Issue by qworld** [pengzhile/atlassian-agent#1]
比如standalone的安装包使用自带的java环境，并不依赖系统安装的java环境。所以想问，您的方法是否对安装方式有要求？

**Comment by pengzhile** [comment]
并不要求安装方式，只需要你能确保服务的java进程带有`-javaagent`参数即可。

**Comment by qworld** [comment]
谢谢，尝试修改 /opt/atlassian/jira/bin/setenv.sh 中的 JAVA_OPTS 变量，修改后启动jira报错，恢复文件后仍然报错，还在研究中。建议其他人尝试

**Comment by pengzhile** [comment]
报的什么错？看一下tomcat的日志。
另外，你使用的jar从哪里来的？

**Comment by pengzhile** [comment]
![image](https://user-images.githubusercontent.com/343491/49775931-faa45300-fd34-11e8-935f-3c331f189ab6.png)

贴一下我编辑的截图，供参考。

**Comment by pengzhile** [comment]
log安装目录`logs/catalina.out`文件。

**Comment by qworld** [comment]
错误信息是:

**Comment by qworld** [comment]
jar 文件用的是release包里的文件。
我修改时没有像你这样另起一行，而是直接在原来的JAVA_OPT变量后面追加上的。
抱歉，平时不用java开发，所以对Tomcat并不熟悉

**Comment by pengzhile** [comment]
你之前使用过试用license?

**Comment by qworld** [comment]
是的，是这个原因吗？ 因为想装几个plugins，所以想试一下你的解决方案。

**Comment by qworld** [comment]
好的，谢谢！我试一下，因为还没正式用，是新装的服务，可以随便折腾。
BTW，是不是正确的方式应该先配置JAVA_OPT，通过keygen获得lisence后再安装服务。如果通过其他方式crack了，再用这个agent会冲突

**Comment by pengzhile** [comment]
一般来说是：
* 安装完成先别启动服务，配置好JAVA_OPTS再启动。
* 不需要其他方式crack，我这个项目是一条龙。
* 启动时看看java进程是否附上了`-javaagent`。

**Comment by qworld** [comment]
非常感谢，我重新按你的方式装一遍，有问题再反馈，谢谢帮助！

**Comment by pengzhile** [comment]
不用客气。
祝使用愉快。

**Comment by aircjm** [comment]
> 那你需要先移除已有license，看你日志报错是这个原因。 applicatin-data/jira/database/h2db.mv.db里。

如何移除已有license
![image](https://user-images.githubusercontent.com/18283183/52615241-7bb3ce00-2ecf-11e9-8ebd-8c32e6dfe475.png)

**Comment by pengzhile** [comment]
> > 那你需要先移除已有license，看你日志报错是这个原因。 applicatin-data/jira/database/h2db.mv.db里。
> 
> 如何移除已有license
> ![image](https://user-images.githubusercontent.com/18283183/52615241-7bb3ce00-2ecf-11e9-8ebd-8c32e6dfe475.png)

application-data/confluence/confluence.cfg.xml 文件内

**Comment by aircjm** [comment]
> > > 那你需要先移除已有license，看你日志报错是这个原因。 applicatin-data/jira/database/h2db.mv.db里。
> > 
> > 
> > 如何移除已有license
> > ![image](https://user-images.githubusercontent.com/18283183/52615241-7bb3ce00-2ecf-11e9-8ebd-8c32e6dfe475.png)
> 
> application-data/confluence/confluence.cfg.xml 文件内

我之前以为是已有license的影响，所以重新安装了一个新的confluence，然后发现还是不行，我是直接加到setenv.sh里面的
![image](https://user-images.githubusercontent.com/18283183/52693688-5cd23c00-2fa2-11e9-8905-b7c4c094611d.png)



在启动参数里面可以看到这个，但是还是依旧无法生成对应的密钥
![image](https://user-images.githubusercontent.com/18283183/52693420-a9694780-2fa1-11e9-8e53-560fc9871c9e.png)



我用的是release里面的打包好的jar，非常感谢
