### ISSUE TITLE
无法激活插件

### ISSUE THREAD

**Issue by seventeenWenT** [pengzhile/atlassian-agent#13]
执行的命令
`java -jar /app/atlassian-agent.jar -p com.atlassian.confluence.extra.team-calendars  -m wentao@qiangshouapp.com  -o https://www.chongdingdahui.com  -s B41Z-POJB-CUBM-SF1H`

**Comment by pengzhile** [comment]
-p tc 

你可以仔细看看 java -jar /app/atlassian-agent.jar 的输出结果。

**Comment by seventeenWenT** [comment]
没有注意到,以为是按照插件的方式.感谢,感谢🙏
