### ISSUE TITLE
What is the right product name for the service desk to generate license key?

### ISSUE THREAD

**Issue by ArmanFeyzi** [pengzhile/atlassian-agent#20]
What is the right product name for the service desk to generate license key?
I try some product name to generate license key but all of them is invalid!
`java -jar atlassian-agent.jar -p jira.service.desk -m aaa@bbb.com -n shcoan -o https://zhile.io -s BDDD-AFJN-ASDF-AE39`

Also i try:
`jira` , `service.desk`, `desk`, `jira-service-desk`

what are the right product name for service desk?

**Comment by pengzhile** [comment]
![image](https://user-images.githubusercontent.com/343491/55855892-51af1d00-5b9b-11e9-95f5-ee677345aed4.png)

**Comment by ArmanFeyzi** [comment]
Thank you, it's working ;)
