### ISSUE TITLE
之前使用其他方式破解过，想更新成这种，提示”那不是一个有效的授权码。“

### ISSUE THREAD

**Issue by yexiaoyu** [pengzhile/atlassian-agent#23]
![image](https://user-images.githubusercontent.com/5335425/56082214-a3300400-5e48-11e9-8cd3-648b0f5b64ab.png)
看confluence启动日志，代理已经启动了。
![image](https://user-images.githubusercontent.com/5335425/56082225-cce92b00-5e48-11e9-9ae3-eabe83c1facb.png)
![image](https://user-images.githubusercontent.com/5335425/56082229-db374700-5e48-11e9-832c-04994f207ae9.png)

**Comment by pengzhile** [comment]
恢复之前被破解的文件，移除之前的老key
