### ISSUE TITLE
Windows环境下JIRA8.1无法正常破解

### ISSUE THREAD

**Issue by actionmoon** [pengzhile/atlassian-agent#29]
步骤1：你可以把：export JAVA_OPTS="-javaagent:/path/to/atlassian-agent.jar ${JAVA_OPTS}"这样的命令放到服务安装所在bin目录下的setenv.sh或setenv.bat（供windows使用）中你可以把：export JAVA_OPTS="-javaagent:/path/to/atlassian-agent.jar ${JAVA_OPTS}"这样的命令放到服务安装所在bin目录下的setenv.sh或setenv.bat（供windows使用）中

问题1：在windows下面setenv.bat，无法使用export导出命令

步骤2：java -jar atlassian-agent.jar -p jira -m aaa@bbb.com -n my_name -o https://zhile.io -s ABCD-1234-EFGH-5678

无法正常激活JIRA8.1！！

**Comment by pengzhile** [comment]
1. setenv.bat对service模式启动的jira不生效，对start-jira.bat启动的生效。
2. setenv.bat里有类似修改JAVA_OPTS的语句，仿照一个，不必死搬export。
3. 建议使用linux。
