### ISSUE TITLE
第三方插件破解问题

### ISSUE THREAD

**Issue by keuse168** [pengzhile/atlassian-agent#5]
尝试破解Goedit时，插件能正常破解，但是Client license无效。

_Your GoEdit Plugin License does not match your GoEdit Client Edition License. Please check the expiry date of your client license and upgrade your subscription. Please contact our support in case that fails._

**Comment by pengzhile** [comment]
没用过Goedit不太清楚。多截几张图看看呢。

**Comment by keuse168** [comment]
从插件本身来看，GoEdit似乎有两个License，分为plugin license and client license。
_GoEdit配置页面截图：_
![2018-12-27 09 16 02](https://user-images.githubusercontent.com/46129372/50461248-19068180-09b8-11e9-9e74-6f354ebc6257.png)
![2018-12-27 09 17 35](https://user-images.githubusercontent.com/46129372/50461275-47845c80-09b8-11e9-8261-1f045f5512a8.png)
_插件管理页面截图：_
![2018-12-27 09 18 41](https://user-images.githubusercontent.com/46129372/50461297-7c90af00-09b8-11e9-97f9-8186b37bfb21.png)

**Comment by pengzhile** [comment]
我看了下，GoEdit Client是连接https://license.goedit.io去校验license，有些脱离atlassian的体系，需要另行研究。

**Comment by keuse168** [comment]
好的，谢谢解答

Neo Peng <notifications@github.com> 于 2018年12月27日周四 10:27写道：

**Comment by szdefine** [comment]
同求解决办法，现在卡这里了，谢谢
