### ISSUE TITLE
Windows server issue

### ISSUE THREAD

**Issue by erdincyildiz** [pengzhile/atlassian-agent#6]
I could see 
============================== agent working =============================

however , at the end it gives an error that says : Jira had problems starting up. I am trying on the latest version Jira 13. 

My JAVA_OPTS in setenv.bat is like this : set JAVA_OPTS= -javaagent:C:\Jira\atlassian-agent.jar %JAVA_OPTS% but no luck.

**Comment by pengzhile** [comment]
Remove your trail license code or crack first.

**Comment by erdincyildiz** [comment]
Still no luck. I've deleted the Jıra server , and have set the agent url before installing it. But no luck.

**Comment by pengzhile** [comment]
Can you upload some screenshots?

**Comment by erdincyildiz** [comment]
Sorry. It was no ones fault. The setting must be like this : set JAVA_OPTS=%JAVA_OPTS% -Xms%JVM_MINIMUM_MEMORY% -Xmx%JVM_MAXIMUM_MEMORY% %JVM_CODE_CACHE_ARGS% %JVM_REQUIRED_ARGS% %DISABLE_NOTIFICATIONS% %JVM_SUPPORT_RECOMMENDED_ARGS% %JVM_EXTRA_ARGS% %JIRA_HOME_MINUSD% %START_JIRA_JAVA_OPTS% -javaagent:C:\Jira\atlassian-agent.jar

Works like a charm.

**Comment by pengzhile** [comment]
Very nice trouble shooting :)

**Comment by erdincyildiz** [comment]
I know that the issue is closed. Just a reminder for windows users. The setting above is for jira. For confluence I've updated the setting in setenv.bat like this : **set CATALINA_OPTS=-Xms1024m -Xmx1024m -XX:+UseG1GC %CATALINA_OPTS% -javaagent:C:\Jira\atlassian-agent.jar** . ;)
