### ISSUE TITLE
无法激活

### ISSUE THREAD

**Issue by aircjm** [pengzhile/atlassian-agent#9]
我之前以为是已有license的影响，所以重新安装了一个新的confluence，然后发现还是不行，我是直接加到setenv.sh里面的
![image](https://user-images.githubusercontent.com/18283183/52693688-5cd23c00-2fa2-11e9-8905-b7c4c094611d.png)

在启动参数里面可以看到这个，但是还是依旧无法生成对应的密钥
![image](https://user-images.githubusercontent.com/18283183/52693420-a9694780-2fa1-11e9-8e53-560fc9871c9e.png)

我用的是release里面的打包好的jar，非常感谢

_Originally posted by @aircjm in https://github.com/pengzhile/atlassian-agent/issues/1#issuecomment-463086581_

**Comment by pengzhile** [comment]
你用什么样的参数生成密钥的？

**Comment by aircjm** [comment]
> 你用什么样的参数生成密钥的？

```shell
/opt/atlassian/confluence/jre/bin/java -jar /opt/atlassian/atlassian-agent.jar -m aircjm@gmail.com -n aircjm -p conf -s BQI2-RQH0-79U3-EDI0
```

**Comment by stoneljq** [comment]
-o 参数是一定要加吗？

**Comment by pengzhile** [comment]
> -o 参数是一定要加吗？

为什么不呢？

**Comment by stoneljq** [comment]
好的，任意可以吗？

**Comment by stoneljq** [comment]
还有个问题请教下，就是-s参数，如果是要crack插件，应该填什么，插件没有server ID的吧？

**Comment by pengzhile** [comment]
> 还有个问题请教下，就是-s参数，如果是要crack插件，应该填什么，插件没有server ID的吧？

还用server的ID，只是-p参数不同。
